### ISSUE TITLE
Not working in 2.83.9

### ISSUE THREAD

**Issue by ikumi90s** [Protinon/Blender-rpc#7]
After importing it to the add-on, when I tried to check on activate it give me this error.

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\[USER]\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\Blender-rpc-master\__init__.py", line 5, in <module>
    from .pypresence import pypresence as rpc
ImportError: cannot import name 'pypresence' from 'Blender-rpc-master.pypresence' (unknown location)

```

**Comment by Protinon** [comment]
You cloned the repository, please download the .zip from the “Releases” section.

Since many issues have been created on this same problem, I’ll leave this one open for others to see.

**Comment by joannevebby** [comment]
I downloaded the latest build 2.1.1, and yes the zip from the releases and I'm also getting this error...

```
Python: Traceback (most recent call last):
  File "C:\Users\joann\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\send2ue\operators.py", line 88, in invoke
    if utilities.is_unreal_connected():
  File "C:\Users\joann\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\send2ue\core\utilities.py", line 664, in is_unreal_connected
    unreal.bootstrap_unreal_with_rpc_server()
  File "C:\Users\joann\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\send2ue\dependencies\unreal.py", line 200, in bootstrap_unreal_with_rpc_server
    raise RuntimeError(result)
RuntimeError: No module named 'rpc'
```
