### ISSUE TITLE
Not working in 3.6

### ISSUE THREAD

**Issue by DVDProjekt** [Protinon/Blender-rpc#18]
Traceback (most recent call last):
  File "C:\Program Files (x86)\......\Blender\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Blender-rpc-master\__init__.py", line 5, in <module>
    from .pypresence import pypresence as rpc
ImportError: cannot import name 'pypresence' from 'Blender-rpc-master.pypresence' (unknown location)

**Comment by Protinon** [comment]
You cloned the repository. Please download the addon from the "Releases" section on Github.
